### PR TITLE
adds door_operator to the docs list

### PR DESCRIPTION
**Pull request by bit-pirate**

### CODE REVIEW

**Comment by bit-pirate** [comment]
Even though we don't use this module right now, I need the documentation up for MediCart documentation.

**Comment by stonier** [comment]
I don't have a door_operator package in my bootstrap workspace?

**Comment by bit-pirate** [comment]
Correct, since we are not using it ATM. It was there for Robotworld 2015. That might have been prior to our work space split or we dropped it in the meanwhile.

Do we need to have it in the bootstrap work space in order to get the docs? Or is the docs list separate?

**Comment by stonier** [comment]
That is what the group keys are to identify - which workspace build they correspond to. Once that workspace build, it then parses this list and builds docs selectively (doesn't do them all).

Add it to `rosinstalls/indigo/gopher_bootstrap-devel.rosinstall` if you'd like the docs for it being built.

**Comment by stonier** [comment]
Do they need to be visible for the medicart project? The devel docs only go to our internal server. To get to the external server, you need to add the package to `gopher_bootstrap-stable.rosinstall` and add this package to the `groot-stable-partners.yaml`.

**Comment by bit-pirate** [comment]
Internally would be fine - just to use as a source for documentation when needed (C&P stuff over). If you like to keep that package out, then I'll just build the docs locally and C&P things into the MediCart documents as needed.

What do you prefer?

**Comment by stonier** [comment]
Internally adding it is fine.

**Comment by bit-pirate** [comment]
Added the door_interactions to the bootstrap workspace. Ready for review and merge.

**Pull request merged**
