### PR TITLE
Fix rsynch binaries target path for groot_arm_binaries

### PR DESCRIPTION
**Pull request by hughie**
External server doesn't have rsync_repositories/yujin/arm directory . 
Change it to /data/file_server/rsync_repositories/yujin.

### CODE REVIEW

**Comment by hughie** [comment]
but .. I don't know how to deploy groot_arm_binaries.

**Comment by stonier** [comment]
> but .. I don't know how to deploy groot_arm_binaries.

Version bump and re-release python-yujin-tools.

**Comment by hughie** [comment]
Thank you for the answer. 

When I did release, I met ```You need a passphrase to unlock the secret key for user" message, 

I'll send e-mail about it to you.

**Comment by hughie** [comment]
I got pypi ownership and it is released. 
There was keylogin problem. but suddenly, it is gone. 
I didn't know what exactly happened. I will look at it more deeply next time.

**Pull request merged**
