### PR TITLE
Apt upgrade all dependencies to latest

### PR DESCRIPTION
**Pull request by asmodehn**
3 scripts with 3 different ways to do basically the same thing. Play with it and let me know...

They have slightly different behavior...
Also I think non of them handle the case where a dependency is marked <version and avoid installing latest, which should be a required behavior...

After investigating all this it seems the proper place to do this would be in - or using - aptitude. There is a lot of possible parameters via command line to do advanced things. https://wiki.debian.org/Aptitude#Advanced_search_patterns

### CODE REVIEW

**Comment by stonier** [comment]
Or debfoster...I'd still like to know if that does everything we're trying to reproduce here.

**Comment by asmodehn** [comment]
The third script is using debfoster. I quickly found a way to list all dependencies, but not to install them. So it s another oneline script ( like apt-rdepends, but without the virtual package problem since it somehow decide which actual package is needed ).

**Comment by stonier** [comment]
Had a quick look.

* what's the virtual package problem?
* so debfoster would need to parse that output it provides and install from that?

Also, when adding scripts here, can you prefix them with a `yujin_`? We've got some legacy ones in there, but in general, this saves having to remember the names of the ones we use where a quick `yujin_<tab><tab>` can refresh our memory.

**Comment by asmodehn** [comment]
Virtual package is like a functionnality provided by multiple packages. The
packaging software need to make a decision on which actual package to
install to satisfy the required functionality.

The debfoster based script here just does that.

**Comment by stonier** [comment]
Playing around with these:
Tried experimenting by attempting an update on the ros package `ros-indigo-base-local-planner`:

`yujin_install_rdepends` recognizes virtual packages, but doesn't know what to do:

```
Package debconf-2.0 is a virtual package provided by:
  debconf 1.5.51ubuntu2
  cdebconf 0.187ubuntu1
You should explicitly select one to install.

Package awk is a virtual package provided by:
  mawk:i386 1.3.3-17ubuntu2
  gawk:i386 1:4.0.1+dfsg-2.1ubuntu2
  original-awk 2012-12-20-1
  mawk 1.3.3-17ubuntu2
  gawk 1:4.0.1+dfsg-2.1ubuntu2
You should explicitly select one to install.
```

`yujin_install_aptgetdepends` does not recognise virtual dependencies and borks:

```
E: Unable to locate package <debconf-2.0>
E: Couldn't find any package by regex '<debconf-2.0>'
E: Unable to locate package <file-rc>
E: Unable to locate package <libblas.so.3>
E: Couldn't find any package by regex '<libblas.so.3>'
E: Unable to locate package <libc-dev>
E: Unable to locate package <libexpat-dev>
E: Unable to locate package <libgl1>
E: Unable to locate package <libgl-dev>
E: Unable to locate package <libglu-dev>
E: Unable to locate package <liblapack.so.3>
E: Couldn't find any package by regex '<liblapack.so.3>'
E: Unable to locate package <libpng-dev>
```

`yujin_install_debfoster` had some problems with dependencies and showed conflicts (maybe getting them in the wrong order?), but after manually installing two of these, it then ran....made alot of noise, but didn't end up upgrading/installing anything.

**Comment by asmodehn** [comment]
- About virtual packages for apt-rdepends, it s explicitely mentionned in the man page under 'BUGS' : http://www.debianadmin.com/manpages/aptrdependsmanpage.htm
package debian QA status : https://tracker.debian.org/pkg/apt-rdepends

- aptgetdepends script is a quick manual attempt to solve the problem. 
Currently stuck at : 
```
alexv@asmodehn:~$ apt-cache show debconf-2.0
N: Can't select versions from package 'debconf-2.0' as it is purely virtual
N: No packages found
```

- debfoster script is just a simulated run for now ( the `-s` here ): 
```
apt-get -s install `debfoster --show-depends $1 | grep "^ " | tr "\n" " "`
```
You want to remove that `-s` when you re ready to mess with your system ( I advise to manually double check all dependencies it returns before though... debfoster has quite a few bugs listed there : https://tracker.debian.org/pkg/debfoster )

**Comment by stonier** [comment]
Surprising just how buggy all of these things are. I think I just took it for granted that it was a simple thing after having done this with gentoo's emerge for so long.

**Comment by stonier** [comment]
Going to close this one out, our yujin ansible framework is doing this job nicely and it can cater for any esoteric problems more easily.

**Pull request closed without merging**
