### PR TITLE
Remove gazebo_ros_pkgs because pull request is merged

### PR DESCRIPTION
**Pull request by AlexReimann**
https://github.com/ros-simulation/gazebo_ros_pkgs/pull/335

### CODE REVIEW

**Comment by bit-pirate** [comment]
Not so fast. :-P

They have merged it, but it hasn't been released yet: http://www.ros.org/debbuild/indigo.html (it is only in shadow-fixed). 

@stonier I'll keep an eye on this and merge it when these they do the next sync with public.

**Comment by stonier** [comment]
Aight, good

On 17 August 2015 at 11:12, Marcus Liebhardt <notifications@github.com>
wrote:

> Not so fast. :-P
>
> They have merged it, but it hasn't been released yet:
> http://www.ros.org/debbuild/indigo.html (it is only in shadow-fixed).
>
> @stonier <https://github.com/stonier> I'll keep an eye on this and merge
> it when these they do the next sync with public.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yujinrobot/yujin_tools/pull/53#issuecomment-131658003>
> .
>



-- 
Phone : +82-10-5400-3296 (010-5400-3296)
Home: http://snorriheim.dnsdojo.com/
Yujin Inno: http://inno.yujinrobot.com/
<http://rnd.yujinrobot.com/>

**Comment by bit-pirate** [comment]
http://www.ros.org/debbuild/indigo.html?q=gazebo_ros

**Comment by bmagyar** [comment]
FYI: The sync has been done, the plugin is out in the open, nothing can stop it now from taking over the world! :)

**Comment by stonier** [comment]
@bmagyar thanks for the heads up!

This was the wrong rosinstall too - it's now deprecated. Removed the proper line in 601338cfe7222980e6ecf013c8da79a0c488d364.

**Pull request closed without merging**
