### PR TITLE
adds yujin_maps

### PR DESCRIPTION
**Pull request by bit-pirate**
I think it would be addition in order to get the latest maps.

### CODE REVIEW

**Comment by stonier** [comment]
Sorry, did not see this one. We still need it?

**Comment by bit-pirate** [comment]
Hmm.

We don't need it for our Gopher robots, since we are changing to a different type of map. But in general yujin_maps would be a good addition to a "yujin_navigation" rosinstaller (e.g. Waiterbot).

**Comment by stonier** [comment]
It's a pretty heavy git clone though. This gets back to the original problem - a git repo for large files isn't the ideal thing. People who actually want to add maps are only about 10% of the use case so I think manually adding it to your workspace is still fine. For the other 90% rosdep'ing the deb is easier.

Speaking of which, we need a solution for collecting 'reference' dslam maps better than the current dslam bag download script at some point. Since it's closed, it would be easy to run a jenkins job to build a deb.

**Comment by bit-pirate** [comment]
Understood.

**Pull request closed without merging**
